stages:          
  - build-image 
  - publish-image 
  - deploy-app 

build-image-job:      
  stage: build-image
  script:
    - docker rm -f ynov_lea_ipti_counter_app_img || true
    - docker build -t ynov_lea_ipti_counter_app_img .
    - docker images

publish-image-job:   
  stage: publish-image
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
    - docker tag ynov_lea_ipti_counter_app_img nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA
    - docker push nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA
    
deploy-app-job:
  stage: deploy-app
  script:
    - echo cat $SSH_PRIVATE_KEY
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no nerlyss@192.168.198.143 'true && docker run --name counter_app -d -p 8080:80 nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA python app.py'
   #'docker rm -f counter_app || 