stages:          
  - build-image # associer au job build-image-job
  - publish-image # associer au job push-image-job
  - deploy-app # associer au job deploy-job

build-image:      
  stage: build-image
  script:
    - docker build -t counter_app_img .
    - docker images

publish-image:   
  stage: publish-image
  script:
    - docker tag counter_app_img nerlyss411/counter_app_img:$CI_COMMIT_SHORT_SHA
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
    - docker push nerlyss411/counter_app_img:$
    
deploy-app:
  stage: deploy-app
  script:
    - sshpass -p "$SSH_PASSWORD" ssh nerlyss@192.168.198.143 'docker rm -f counter_app || true && docker run --name counter_app -d -p 8080:80 nerlyss411/counter_app_img:$CI_COMMIT_SHORT_SHA'
  tags:
    - gitlab-runner
