stages:          
  - build-image 
  - publish-image 
  - deploy-app 

build-image-job:      
  stage: build-image
  script:
    - docker rm -f ynov_lea_ipti_counter_app_img || true
    - docker build -t ynov_lea_ipti_counter_app_img .
    - docker images

publish-image-job:   
  stage: publish-image
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
    - docker tag ynov_lea_ipti_counter_app_img nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA
    - docker push nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA
    
deploy-app-job:
  stage: deploy-app
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no nerlyss@192.168.198.143
    #ssh -i /home/nerlyss/.ssh/id_rsa nerlyss@192.168.198.143 'docker rm -f counter_app || true && docker run --name counter_app -d -p 8080:80 nerlyss411/ynov_lea_ipti_counter_app_img:$CI_COMMIT_SHORT_SHA python app.py'
    #ssh nerlyss@192.168.198.143
